name: Python PySDD package

on:
  push:
    branches: [ deploy ]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        #os: [ubuntu-latest, macos-13, macos-14]
        os: [ubuntu-latest]


    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          # configure cibuildwheel to build native archs ('auto') and ARM64
          # CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_LINUX: aarch64
          CIBW_SKIP: cp36-* cp37-* pp* *musllinux*  *i686 *ppc64le *s390x *win_arm64*
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
          CIBW_BEFORE_BUILD: "pip install SCons && cd pysdd/lib/libsdd-2.0 && scons && cp build/* ../sdd-2.0/lib/"